version: '2.1'
services:
  nginx:
    image: nginx:1.10
    ports:
      - "9100:443"
    links:
      - api-server
    volumes:
      - ./src/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/nginx/etc/nginx/includes/security-headers.conf:/etc/nginx/includes/security-headers.conf
      - ./src/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./src/nginx/srv/dist:/srv/dist:ro
  app-frontend:
    image: node:6.9-slim
    working_dir: /usr/src
    links:
      - nginx
    ports:
      - "8284:8284"
    volumes:
        - ./src/app-frontend:/usr/src
        - ./src/nginx/srv/dist:/usr/src/static
        # Ensure node_modules cache doesn't clash with other jobs on CI.
        - /var/cache/pc-demo-node-modules:/usr/src/node_modules
    entrypoint: npm
    command: run dev-server
  api-server:
    image: openjdk:8-jre
    ports:
      - "9000:9000"
    volumes:
        - ./src/app-backend/:/opt/app-backend/
        - ./data/catalog-hadoop:/opt/catalog-hadoop/
        - ./data/catalog:/opt/catalog/
        - ./src/app-backend/.sbt:/root/.sbt
        - /home/vagrant/.ivy2/:/root/.ivy2
        - $HOME/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE=open-tree-id
    working_dir: /opt/app-backend/
    entrypoint: ./sbt
    command: ~server/reStart
